apiVersion: "v1"
kind: Pod
metadata:
  name: cloud-fund-backend
  labels:
    app: cloud-fund-backend
    env: test
spec:
  containers:
  - name: cloud-fund-backend
    image: us.icr.io/cloud-fund-python/cloud-fund-backend-sgx
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: cloud-fund-environment-secrets
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: cloud-fund-environment-secrets
          key: password
    - name: SECRET_DBCONN
      valueFrom:
        secretKeyRef:
          name: cloud-fund-environment-secrets
          key: dbconn
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: cloud-fund-environment-secrets
          key: db_name
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: cloud-fund-environment-secrets
          key: API_KEY
    - name: KP_INSTANCE_ID
      valueFrom:
        secretKeyRef:
          name: cloud-fund-environment-secrets
          key: kp_instance_id
    - name: CRK_ID
      valueFrom:
        secretKeyRef:
          name: cloud-fund-environment-secrets
          key: crk_id
    - name: NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: NODE_AGENT_BASE_URL
      value: http://$(NODE_IP):9092/v1
    volumeMounts:
    - mountPath: /dev/isgx
      name: isgx
    - mountPath: /dev/gsgx
      name: gsgx
    - mountPath: /var/run/aesmd/aesm.socket
      name: aesm-socket
    - name: secret-volume
      mountPath: /etc/secret-volume
  volumes:
  - name: isgx
    hostPath:
      path: /dev/isgx
      type: CharDevice
  - name: gsgx
    hostPath:
      path: /dev/gsgx
      type: CharDevice
  - name: aesm-socket
    hostPath:
      path: /var/run/aesmd/aesm.socket
      type: Socket
  - name: secret-volume
    secret:
      secretName: cloud-fund-environment-secrets
