apiVersion: "v1"
kind: Pod
metadata:
  name: cloud-fund-backend
  labels:
    app: cloud-fund-backend
    env: test
spec:
  containers:
  - name: cloud-fund-backend
    image: us.icr.io/cloud-fund-python/cloud-fund-backend
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: cloud-fund-environment-secrets
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: cloud-fund-environment-secrets
          key: password
    - name: SECRET_DBCONN
      valueFrom:
        secretKeyRef:
          name: cloud-fund-environment-secrets
          key: dbconn
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: cloud-fund-environment-secrets
          key: db_name
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: cloud-fund-environment-secrets
          key: API_KEY
    - name: KP_INSTANCE_ID
      valueFrom:
        secretKeyRef:
          name: cloud-fund-environment-secrets
          key: kp_instance_id
    - name: CRK_ID
      valueFrom:
        secretKeyRef:
          name: cloud-fund-environment-secrets
          key: crk_id
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret-volume
    ports:
    - name: http
      containerPort: 8500
      protocol: TCP
  volumes:
  - name: secret-volume
    secret:
      secretName: cloud-fund-environment-secrets
